### ISSUE TITLE
Add config system

### ISSUE THREAD

**Issue by ItayNaveh** [ShaharNaveh/snadra#77]
make a config system that either reads a `~/.config/snadra` file or checks enviorment variables or command line arguments
example fields:
- postgres_host
- postgres_port
- postgres_user
- postgres_password

and others

**Comment by ShaharNaveh** [comment]
@ItayNaveh If you intend to work on this, please LMK:)

**Comment by ItayNaveh** [comment]
I will work on it either today or thursday

**Comment by ShaharNaveh** [comment]
> I will work on it either today or thursday

Do it whenever you want/can :)

**Comment by ItayNaveh** [comment]
`toml` has not been updated in a while.
we should consider using either [tomli](https://github.com/hukkinj1/tomli) or [pytomlpp](https://github.com/bobfang1992/pytomlpp)

**Comment by ShaharNaveh** [comment]
> `toml` has not been updated in a while.
> we should consider using either [tomli](https://github.com/hukkinj1/tomli) or [pytomlpp](https://github.com/bobfang1992/pytomlpp)

I think that we will go with ```pytomlpp```

**Comment by ItayNaveh** [comment]
resolved by #95
